FROM php:8.2.0-apache

WORKDIR /app

RUN apt-get update && \
    apt-get install -y libxml2-dev

RUN docker-php-ext-install mysqli bcmath

RUN docker-php-ext-install soap && docker-php-ext-enable soap

RUN a2enmod rewrite

RUN rm -rf /var/www/html && \
    ln -s /app /var/www/html

RUN pecl install xdebug && docker-php-ext-enable xdebug \
&& echo "\n\
xdebug.start_with_request=yes \n\
xdebug.discover_client_host=1 \n\
#xdebug.client_host=host.docker.internal \n\
xdebug.output_dir = /tmp/docker-xdebug \n\
" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini